matos/urls.py
from django.urls import path, re_path

from .views import *

urlpatterns = [
    path('', PieceListView.as_view(), name='pieces-list'),
    path('piece/new', PieceCreateView.as_view(), name='piece-create'),
    path('piece/<int:pk>/', PieceDetailView.as_view(), name='piece-view'),
    re_path(r'^piece/(?P<pk>\d+)/update', PieceUpdateView.as_view(), name='piece-update'),
    path('piece/<int:pk>/delete', PieceDeleteView.as_view(), name='piece-delete'),
    path('loan/', LoanListView.as_view(), name='loan-list'),
    path('loan/new', LoanCreateView.as_view(), name='loan-create'),
    path('loan/<int:pk>/', LoanDetailView.as_view(), name='loan-view'),
    path('loan/<int:pk>/update', LoanUpdateView.as_view(), name='loan-update'),
    path('loan/<int:pk>/delete', LoanDeleteView.as_view(), name='loan-delete'),
    path('loan/<int:pk>/back', LoanBackView.as_view(), name='loan-back'),
]

matos/models.py
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from matos.app_settings import app_settings


class Location(models.Model):
    label = models.CharField(_('Location'), max_length=50)
    colour_code = models.CharField(_('Colour code'), max_length=20, default='#ffffff')

    class Meta:
        ordering = ['label']

    def __str__(self):
        return self.label


class Piece(models.Model):
    class Meta:
        verbose_name = _('Piece')
        verbose_name_plural = _('Pieces')
        ordering = ['title']

    title = models.CharField(_('Title'), max_length=50)
    reference = models.CharField(_('Reference'), max_length=50, blank=True)
    comment = models.TextField(_('Comment'), blank=True)
    location = models.ForeignKey(
        Location, verbose_name=_('Location'), null=True, blank=True, on_delete=models.SET_NULL
    )
    location_details = models.TextField(_('Location Details'), blank=True)
    image = models.ImageField(_('Picture'), upload_to='matos', max_length=250, null=True, blank=True)

    manual_file = models.FileField(_('Manual (file)'), upload_to='matos', null=True, blank=True)
    manual_url = models.URLField(_('Manual (URL)'), max_length=255, null=True, blank=True)

    in_use = models.BooleanField(_('In use'), default=False)
    rentable = models.BooleanField(_('Rentable'), default=False)
    quantity = models.IntegerField(_('Quantity'), default=1, null=True)

    purchase_date = models.DateField(_('Purchase Date'), null=True, blank=True)
    purchase_price = models.DecimalField(
        _('Purchase Price'), max_digits=10, decimal_places=2, null=True, blank=True
    )
    insurance_category = models.CharField(_('Insurance category'), max_length=20, blank=True, default='')

    creation_timestamp = models.DateTimeField(auto_now_add=True, null=True)
    last_update_timestamp = models.DateTimeField(auto_now=True, null=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('piece-view', kwargs={'pk': self.id})


class Loan(models.Model):
    class Meta:
        verbose_name = _('Loan')
        verbose_name_plural = _('Loans')

    date_start = models.DateField(_('Start date'), null=True)
    date_end = models.DateField(_('End date'), null=True)
    loaner = models.CharField(_('Loaner'), blank=True, max_length=50)
    loaner_email = models.EmailField(_('Loaner email'), blank=True)
    items = models.ManyToManyField(Piece, verbose_name=_('Items'), blank=True)
    comment = models.TextField(_('Comment'), blank=True)

    back_timestamp = models.DateTimeField(null=True)

    def get_absolute_url(self):
        return reverse('loan-view', kwargs={'pk': self.id})

    def lateness(self):
        if self.back_timestamp:
            lateness = (self.back_timestamp.date() - self.date_end).days
        else:
            lateness = (now().date() - self.date_end).days
        if lateness > 0:
            return lateness
        return 0

matos/templates/matos/base.html
{% extends "base.html" %}
{% load i18n %}

{% block more-user-links %}
  {{ block.super }}
  {% if perms.matos.add_piece %}
    <a class="button icon-hardware-inventory" href="{% url 'pieces-list' %}">{% trans 'Inventory' %}</a>
  {% endif %}
{% endblock %}

matos/templates/matos/base_loans.html
{% extends "base.html" %}
{% load i18n %}

{% block more-user-links %}
  {{ block.super }}
  {% if perms.matos.add_loan %}
    <a class="button icon-loans" href="{% url 'loan-list' %}">{% trans 'Loans' %}</a>
  {% endif %}
{% endblock %}

matos/templates/matos/basket-items.html
<ul id="selected-items"></ul>
<span style="display: none">
  {% include "django/forms/widgets/select.html" %}
</span>

matos/templates/matos/loan_confirm_delete.html
{% extends "matos/base_loans.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{{ object.date_start }} → {{ object.date_end }}</h2>
{% endblock %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    <div class="buttons">
      <button>{% trans 'Confirm' %}</button>
      <a class="cancel" href=".">{% trans "Cancel" %}</a>
    </div>
  </form>

{% endblock %}

matos/templates/matos/loan_detail.html
{% extends "matos/base_loans.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{{ object.date_start }} → {{ object.date_end }}</h2>
{% endblock %}

{% block content %}
  <div class="section bo-block">

    {% if object.back_timestamp %}
      <p><strong>{% trans "Marked as back on:" %} {{ object.back_timestamp }}</strong></p>
    {% endif %}

    <p>{{ object.loaner }}</p>

    <ul>
      {% for piece in pieces %}
        <li><a href="{% url 'piece-view' pk=piece.id %}">{{ piece.title }}</a>
          {% if piece.current_loans %}
            <span class="current-loans">⚠️
              {% for loan in piece.current_loans %}
                <span>{{ loan.date_start }} → {{ loan.date_end }}</span>
                {% if not forloop.last %}, {% endif %}
              {% endfor %}
            </span>
          {% endif %}
        </li>
      {% endfor %}
    </ul>

    {% if object.comment %}
      <p>
        {{ object.comment }}
      </p>
    {% endif %}

    <p>
      <a class="pk-button" href="{% url 'loan-update' pk=loan.id %}">{% trans 'Edit Details' %}</a>
      {% if not object.back_timestamp%}
        <a class="pk-button" href="{% url 'loan-back' pk=loan.id %}">{% trans 'Mark as back' %}</a>
        <a class="pk-button delete-button" data-popup style="float: right;"
           href="{% url 'loan-delete' pk=loan.id %}">{% trans 'Cancel loan' %}</a>
      {% endif %}
    </p>

  </div>
{% endblock %}

matos/templates/matos/loan_form.html
{% extends "matos/base_loans.html" %}
{% load gadjo i18n %}

{% block appbar %}
  {% if object %}
    <h2>{{ object.date_start }} → {{ object.date_end }}</h2>
    <span class="actions"><a href="{% url 'loan-view' pk=object.id %}">{% trans 'Back to Loan' %}</a></span>
  {% else %}
    <h2>{% trans 'New Loan' %}</h2>
  {% endif %}
{% endblock %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    <div id="form-content">
      {% csrf_token %}
      <div class="matos-loan-form">

        <div class="loan-infos">
          {{ form|with_template }}
        </div>

        <div class="loan-available-items">
          <h3>{% trans 'Available items:' %}</h3>
          <div id="locations-legend">
            <ul>
              {% for location in locations %}
                <li><a
                  style="border-color: {{ location.colour_code }}"
                  href="#"
                  data-location-id="{{ location.id }}">{{ location.label }}</a></li>
              {% endfor %}
            </ul>
          </div>
          <div>
            <input type="search" id="search-q" name="q" placeholder="{% trans "Search..." %}" autocomplete="off">
          </div>

          <ul class="available-items">
            {% for piece in pieces %}
              <li data-location-id="{{ piece.location_id }}"
                  data-piece-label-slug="{{ piece.title|slugify }}"
              ><button data-piece-id="{{ piece.id }}"
                ><span class="piece-label">{{ piece.title }}</span>
                  {% if piece.current_loans %}
                    <span class="current-loans">⚠️
                      {% for loan in piece.current_loans %}
                        <span>{{ loan.date_start }} → {{ loan.date_end }}</span>
                        {% if not forloop.last %}, {% endif %}
                      {% endfor %}
                    </span>
                  {% endif %}</button></li>
            {% endfor %}
          </ul>
        </div>

      </div>


      {% block buttons %}
        <div class="buttons">
          <button>{% trans 'Save' %}</button>
          <a class="cancel" href=".">{% trans "Cancel" %}</a>
        </div>
      {% endblock %}
    </div>
  </form>

  {{ members|json_script:"members-data" }}

{% endblock %}

{% block page-end %}
  <script>
    $(document).ready(function() {
      $('#locations-legend a').click(function() {
        var active = $(this).parent().is('.active');
        $(this).parent().parent().find('.active').removeClass('active')
        if (active) {
          $('.available-items li').show();
        } else {
          $(this).parent().addClass('active')
          $('.available-items li').hide();
          $('.available-items li[data-location-id="' + $(this).attr('data-location-id') + '"]').show();
        }
        return false;
      });
      $('#search-q').on('change keyup paste', function() {
        const q = $(this).val();
        if (q) {
          $('#locations-legend .active').removeClass('active');
          $('.available-items li').hide();
          $('.available-items li[data-piece-label-slug*="' + q + '"]').show();
        } else {
          $('.available-items li').show();
        }
      });

      function move_list(elem) {
        var piece_id = $(elem).data('piece-id');
        var option = $('#id_items option[value="' + piece_id + '"]');
        if (option.prop('selected')) {
          $(elem).parent().detach().appendTo('#selected-items');
        } else {
          $(elem).parent().detach().prependTo('.available-items');
        }
      }
      $('.available-items button').click(function() {
        var piece_id = $(this).data('piece-id');
        var option = $('#id_items option[value="' + piece_id + '"]');
        option.prop('selected', ! option.prop('selected'));
        move_list(this);
        return false;
      });
      $('.available-items button').each(function() { move_list(this) });

      const members = JSON.parse(document.getElementById('members-data').textContent);
      $('#id_loaner').on('keyup', function() {
        var value = $(this).val().toLowerCase();
        var $ul = $('<ul>');
        var hits = false;
        if (value.length > 2) {
          for (member of members) {
            if (member.slugged_name.indexOf(value) > -1) {
              var $li = $('<li>', {text: member.name, 'data-email': member.email});
              $li.on('click', function() {
                $('#id_loaner').val($(this).text());
                $('#id_loaner_email').val($(this).data('email'));
                $('.loaner-info').empty();
              });
              $li.appendTo($ul);
              hits = true;
            }
          }
        }
        $('.loaner-info').empty();
        if (hits) {
          $ul.appendTo($('.loaner-info'));
        }
      });
    });
  </script>
{% endblock %}

matos/templates/matos/loan_list.html
{% extends "matos/base_loans.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{% trans 'Current loans' %}</h2>
  <span class="actions"><a href="{% url 'loan-create' %}">{% trans 'New loan' %}</a></span>
{% endblock %}

{% block content %}
  {% include "matos/loan_table.html" with loan_list=object_list %}
{% endblock %}

matos/templates/matos/loan_table.html
{% load i18n %}

<table class="main">
  <thead>
    <tr>
      <th>{% trans "Start date" %}</th>
      <th>{% trans "End date" %}</th>
      <th>{% trans "Lateness" %}</th>
      <th>{% trans "Loaner" %}</th>
    </tr>
  </thead>
  <tbody>
    {% now "Y-d-m" as current_day %}
    {% for loan in loan_list %}
      <tr>
        <td>{{ loan.date_start }}</td>
        <td>{{ loan.date_end }}
          {% if loan.back_timestamp %}
            <br>
            {% blocktrans trimmed with back_date=loan.back_timestamp|date:"SHORT_DATE_FORMAT" %}
              (back on {{ back_date }})
            {% endblocktrans %}
          {% endif %}
        </td>
        <td>{% if loan.lateness %}{% blocktrans count counter=loan.lateness %}{{ counter }} day{% plural %}{{ counter }} days{% endblocktrans %}{% endif %}</td>
        <td>{{ loan.loaner }}</td>
        <td><a class="pk-button" href="{% url 'loan-view' pk=loan.id %}">{% trans "Details" %}</a></td>
      </tr>
    {% endfor %}
  </tbody>
</table>

matos/templates/matos/loaner-input.html
{% include "django/forms/widgets/input.html" %}
<div class="loaner-info"></div>

matos/templates/matos/piece_confirm_delete.html
{% extends "matos/base.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{{ object.title }}</h2>
  <span class="actions"><a href="{% url 'piece-view' pk=object.id %}">{% trans 'Back to Piece' %}</a></span>
{% endblock %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    <button>{% trans 'Confirm Deletion' %}</button>
  </form>

{% endblock %}

matos/templates/matos/piece_detail.html
{% extends "matos/base.html" %}
{% load i18n thumbnail %}

{% block appbar %}
  <h2>{{ object.title }}</h2>
  {% if perms.matos.add_piece %}
    <span class="actions">
      <a class="delete-button" href="{% url 'piece-delete' pk=piece.id %}">{% trans 'Delete' %}</a>
      <a href="{% url 'piece-update' pk=piece.id %}">{% trans 'Edit Details' %}</a>
    </span>
  {% endif %}
{% endblock %}

{% block content %}

  {% if object.image %}
    <div id="piece-details">
      {% thumbnail object.image "200" as im %}
        <a href="{{ object.image.url }}"><img src="{{ im.url }}"/></a>
      {% endthumbnail %}
    </div>
  {% endif %}

  <div class="section">
    <h3>{% trans 'Infos' %}</h3>
    {% if object.reference or object.purchase_date or object.purchase_price or object.manual_file or object.manual_url %}
      <ul>
        {% if object.manual_file %}
          <li><a href="{{ object.manual_file.url }}">{% trans 'Manual (PDF)' %}</a></li>
        {% endif %}
        {% if object.manual_url %}
          <li><a href="{{ object.manual_url }}" target="blank" nopener>{% trans 'Manual' %}</a></li>
        {% endif %}
        {% if object.reference %}
          <li>{% trans 'Reference' %}: {{ object.reference }}</li>
        {% endif %}
        {% if object.purchase_date %}
          <li>{% trans 'Purchase Date' %}: {{ object.purchase_date }}</li>
        {% endif %}
        {% if object.purchase_price %}
          <li>{% trans 'Purchase Price' %}: {{ object.purchase_price }} €</li>
        {% endif %}
      </ul>
    {% endif %}

    {% if object.comment %}
      <h3>{% trans 'Comment' %}</h3>
      <div>
        <p>
          {{ object.comment }}
        </p>
      </div>

    {% endif %}

    {% if object.location or object.location_details %}
      <h3>{% trans 'Location' %}</h3>
      <div>
        {% if object.location %}<p>{{ object.location }}</p>{% endif %}
        {% if object.location_details %}<p>{{ object.location_details }}</p>{% endif %}
      </div>
    {% endif %}

    {% if latest_loans %}
      <h3>{% trans 'Latest loans' %}</h3>
      <div>
        {% include "matos/loan_table.html" with loan_list=latest_loans %}
      </div>
    {% endif %}

  </div>

{% endblock %}

matos/templates/matos/piece_form.html
{% extends "matos/base.html" %}
{% load i18n %}

{% block appbar %}
  {% if object %}
    <h2>{{ object.title }}</h2>
    <span class="actions"><a href="{% url 'piece-view' pk=object.id %}">{% trans 'Back to Piece' %}</a></span>
  {% else %}
    <h2>{% trans 'New Piece' %}</h2>
  {% endif %}
{% endblock %}


{% block content %}
  <form method="post" enctype="multipart/form-data">
    <div id="form-content" class="matos-piece">
      {% csrf_token %}
      {{ form.as_p }}
    </div>
    {% block buttons %}
      <div class="buttons">
        <button>{% trans 'Save' %}</button>
        <a class="cancel" href="{% if object %}.{% else %}..{% endif %}">{% trans "Cancel" %}</a>
      </div>
    {% endblock %}
  </form>
{% endblock %}

matos/templates/matos/piece_list.html
{% extends "matos/base.html" %}
{% load i18n %}

{% block appbar %}
  <h2>{% trans 'Inventory' %}</h2>
  <span class="actions">
    <a class="extra-actions-menu-opener"></a>
    <ul class="extra-actions-menu">
      <li><a href=".">Tout afficher</a></li>
      {% for location in locations %}
        <li><a href="?location={{ location.id }}">{{ location.label }}</a></li>
      {% endfor %}
    </ul>
    {% if perms.matos.add_piece %}
      <a href="{% url 'piece-create' %}">{% trans 'New Piece' %}</a>
    {% endif %}
  </span>
{% endblock %}

{% block content %}

  <div id="locations-legend">
    <ul>
      {% for location in locations %}
        <li
          {% if location.id|stringformat:"s" == location_id %}class="active"{% endif %}
        ><a
          style="border-color: {{ location.colour_code }}"
          {% if location.id|stringformat:"s" == location_id %}
            href="."
          {% else %}
            href="?location={{ location.id }}"{% endif %}>{{ location.label }}</a></li>
      {% endfor %}
    </ul>
  </div>

  {% if rentable %}
    <div class="section">
      <h3>Pour sorties</h3>

      <ul class="pieces-list">
        {% for piece in rentable %}
          <li style="border-color: {{ piece.location.colour_code }}"><a href="{% url 'piece-view' pk=piece.id %}">{{ piece.title }}</a></li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}

  {% if stock %}
    <div class="section">
      <h3>Stock</h3>

      <ul class="pieces-list">
        {% for piece in stock %}
          <li style="border-color: {{ piece.location.colour_code }}"><a href="{% url 'piece-view' pk=piece.id %}">{{ piece.title }}</a></li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}

  {% if in_use %}
    <div class="section">
      <h3>Utilisé à la radio</h3>

      <ul class="pieces-list">
        {% for piece in in_use %}
          <li style="border-color: {{ piece.location.colour_code }}"><a href="{% url 'piece-view' pk=piece.id %}">{{ piece.title }}</a></li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}

{% endblock %}